name: scrobblenaut
description: A deadly simple LastFM API Wrapper for Dart. So deadly simple that it's gonna hit the mark.
version: 3.0.0
homepage: https://github.com/Nebulino/Scrobblenaut
issue_tracker: https://github.com/Nebulino/Scrobblenaut/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  json_annotation: ^4.0.1
  convert: ^3.0.0
  dio: ^5.3.0
  crypto: ^3.0.1
  xml: ^6.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.24.4
  json_serializable: ^6.7.1
  build_runner: ^2.0.4
